name: kokoro
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - kokoro>=0.9.4
      - soundfile
      - misaki[en]
      - --index-url https://download.pytorch.org/whl/cu121
      - torch
      - torchvision
      - torchaudio